# Generated by Django 2.0.7 on 2018-08-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180801_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterField(
            model_name='article',
            name='digest',
            field=models.CharField(blank=True, help_text='可选项，若为空则摘要取正文前256个字符', max_length=512),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
