"""auth_mail

Revision ID: 79265e782a4c
Revises: 1dc555c7b2c9
Create Date: 2018-03-19 20:14:31.627974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79265e782a4c'
down_revision = '1dc555c7b2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
