# Generated by Django 2.0.7 on 2018-08-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180807_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='digest_img',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='digest',
            field=models.CharField(blank=True, help_text='可选项，若为空则摘要取正文前128个字符', max_length=512),
        ),
    ]
